[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
description = "A fast and limited-memory structure with a landmask based on GSHHG for determing whether a point on Earth is on land or in the ocean"
name = "roaring-landmask"
version = "0.1.0"
edition = "2018"

[lib]
name = "roaring_landmask"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "make_bitmap"
path = "src/devel/make_bitmap.rs"

[dependencies]
geo = "0.18.0"
geos = "8.0.0"
lazy_static = "1.4.0"
numpy = "0.13.1"
pyo3 = "0.13.2"
roaring = "0.7.0"
wkb = "0.7.1"
xz2 = "0.1.6"

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]

[profile.release]
debug = true

